pipeline:
  name: ECS-Cluster
  identifier: ECSCluster
  projectIdentifier: AWS
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: custom
        identifier: custom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack
                  identifier: CreateStack
                  spec:
                    provisionerIdentifier: Cluster
                    configuration:
                      stackName: cluster-1
                      connectorRef: AWS
                      region: ap-southeast-2
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - 22_task_harness.yaml
                              connectorRef: GitHub
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: VpcId
                          value: <+input>
                          type: String
                        - name: SubnetIds
                          value: <+env.variables.SubnetId>
                          type: String
                  timeout: 10m
        tags: {}
    - stage:
        name: Dev-Deploy
        identifier: DevDeploy
        description: ""
        type: Deployment
        spec:
          deploymentType: ECS
          service:
            serviceRef: ClusterCreation
          environment:
            environmentRef: Dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: AWSDevapsoutheast2
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: ECS
                    configuration:
                      stackName: stack-1-ecs
                      connectorRef: AWS
                      region: ap-southeast-2
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - 22_task_harness.yaml
                              connectorRef: GitHub
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: VpcId
                          value: <+input>
                          type: String
                        - name: SubnetIds
                          value: <+input>
                          type: String
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
