pipeline:
  name: ECS-Cluster
  identifier: ECSCluster
  projectIdentifier: AWS
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: custom
        identifier: custom
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack
                  identifier: CreateStack
                  spec:
                    provisionerIdentifier: Cluster
                    configuration:
                      stackName: cluster-1
                      connectorRef: AWS
                      region: ap-southeast-2
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - 22_task_harness.yaml
                              connectorRef: GitHub
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: VpcId
                          value: <+input>
                          type: String
                        - name: SubnetIds
                          value: <+env.variables.SubnetId>
                          type: String
                  timeout: 10m
        tags: {}
