pipeline:
  name: KubeCluster
  identifier: KubeCluster
  projectIdentifier: EKS
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: KubeService
          environment:
            environmentRef: KubeDevuseast1
            deployToAll: false
            infrastructureDefinitions:
              - identifier: KubeDev
          execution:
            steps:
              - step:
                  type: K8sBlueGreenDeploy
                  name: K8sBlueGreenDeploy_1
                  identifier: K8sBlueGreenDeploy_1
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    skipUnchangedManifest: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
