pipeline:
  name: KubeCluster
  identifier: KubeCluster
  projectIdentifier: EKS
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: KubeService
          environment:
            environmentRef: KubeDevuseast1
            deployToAll: false
            infrastructureDefinitions:
              - identifier: KubeDev
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack
                  identifier: CreateStack
                  spec:
                    provisionerIdentifier: EKS
                    configuration:
                      stackName: Eks-Harness
                      connectorRef: AWS
                      region: us-east-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - 22_eks_h.yaml
                              connectorRef: GitHub
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: EKSClusterName
                          value: <+input>
                          type: String
                        - name: EKSNodeGroupName
                          value: <+input>
                          type: String
                        - name: VpcId
                          value: <+input>
                          type: String
                        - name: SubnetId1
                          value: <+input>
                          type: String
                        - name: SubnetId2
                          value: <+input>
                          type: String
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
