pipeline:
  name: testttttt1-t2
  identifier: testttttt1
  projectIdentifier: S3
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: c-s
        identifier: cs
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: AWS
                    configuration:
                      stackName: stackkkkkkkkkkk1
                      connectorRef: AWS
                      region: ap-southeast-2
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - Lab 2.3.1-Versioning.yaml
                              connectorRef: GitHub
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: bucketb
                          value: <+pipeline.variables.bucketb>
                          type: String
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript
                  identifier: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_2
                  identifier: ShellScript_2
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          pip install awscli
                          chmod +x install_aws_cli.sh
                          ./install_aws_cli.sh
                          GITHUB_URL="https://github.com/JanjanamSurekha/H-R/blob/main/test1%2C2.zip"
                          S3_BUCKET="jvvtttssss1"
                          aws s3 cp test1,2.zip "s3://$S3_BUCKET"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: bucketb
      type: String
      description: ""
      required: false
      value: <+input>
