pipeline:
  name: testings3
  identifier: testings3
  projectIdentifier: S3
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: c-s
        identifier: cs
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: abc
                    configuration:
                      stackName: ssss-1
                      connectorRef: AWS
                      region: ap-southeast-2
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - Lab 1.1.1-CFN.yaml
                              connectorRef: GitHub
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: bucketb
                          value: <+pipeline.variables.bucketb>
                          type: String
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: bucketb
      type: String
      description: ""
      required: true
      value: <+input>
