AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for creating ECS Cluster"
Parameters:
  ECSClusterName:
    Type: String
    Default: DemoCluster2
  ECSServiceName:
    Type: String
    Default: serviceee2
  VpcId:
    Type: String
    Default: ' '
  SubnetIds:
    Type: String
    Default: ' '
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: 
        - FARGATE
      ClusterName: !Ref ECSClusterName
      Tags:
        - Key: "ECS"
          Value: "Cluster"
  ECSTaskDefnition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions: 
        - Name: container
          Image: nginx:latest
      Cpu: "256"
      Family: ttttttttt2
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities: 
        - FARGATE
      Tags:
        - Key: "ECS"
          Value: "Task"
  ECSService:
    Type: AWS::ECS::Service
    Properties: 
      ServiceName: !Ref ECSServiceName
      Cluster: !Ref ECSClusterName
      DesiredCount: 1
      LaunchType: FARGATE
      SchedulingStrategy: REPLICA
      PlatformVersion: LATEST
      NetworkConfiguration: 
          AwsvpcConfiguration:
              AssignPublicIp: ENABLED
              SecurityGroups:
                - sg-0a763f0309ed99d8b
              Subnets: 
                - !Ref SubnetIds
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false
      EnableECSManagedTags: true
      TaskDefinition: !Ref ECSTaskDefnition
      Tags:
        - Key: "ECS"
          Value: "Service"
  
