AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda behind API Gateway"
Resources:
  JvtsLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: JvtsLF
      Runtime: python3.8
      Role: !GetAtt JvtsIamRole.Arn
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          import json

          def lambda_handler(event, context):
              # TODO implement
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello AWS!')
              }
    DependsOn:
      - JvtsIamRole
  JvtsIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: lambda
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
  