AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Versioning"
Parameters:
  bucketb:
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref bucketb
      VersioningConfiguration:
        Status: Enabled

