AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for S3 Bucket"
Parameters:
  bucketb:
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: Fn::GetAtt ${bucketb}
      
